### ISSUE TITLE
Add few examples for beginners

### ISSUE THREAD

**Issue by fjouatte** [juanifioren/django-oidc-provider#100]
Consider adding few examples for beginners

**Comment by juanifioren** [comment]
Yup! you are right. Btw, do you mean examples about the protocol or how to use the package?.
Greetings!

**Comment by fjouatte** [comment]
Both will be great don't you think ? I mean just tiny examples about protocol and more detailed examples for the use of the package

**Comment by juanifioren** [comment]
Created the examples section in docs. The idea is to add more.
http://django-oidc-provider.readthedocs.io/en/develop/sections/examples.html
