### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by fjouatte** [juanifioren/django-oidc-provider#101]
Translate in french

**Comment by juanifioren** [comment]
Already generate the .po files so you can send a pull request with the strings translated.

https://github.com/juanifioren/django-oidc-provider/blob/v0.3.x/oidc_provider/locale/fr/LC_MESSAGES/django.po

Waiting for your contribution! Thanks!

**Comment by fjouatte** [comment]
Awesome, i'll do that soon :)
