### ISSUE TITLE
Extending Client model

### ISSUE THREAD

**Issue by davidmr** [juanifioren/django-oidc-provider#116]
Hi,

I was wondering if it's possible to extend the Client model to add custom fields. One of such fields could be the privacy policy of the Client or something similar that can be used in the consent screen.

Thanks in advance.

**Comment by juanifioren** [comment]
Hi, not possible at this moment. What do you mean with privacy policy? a text field to enter some kind of terms of condition?. Feel free to propose any other field that you think must be in Client model.

Greetings.

**Comment by davidmr** [comment]
For example when you create your client (relaying party) information at Google, you can add the Homepage URL, Product logo URL, Privacy policy URL and Terms of Service URL.

So I was thinking on making possible to somehow extend the Client model depending on what the OIDC provider needs or wants to offer its clients. 

The mechanism could be something similar to how Django allows to change the User model.

**Comment by juanifioren** [comment]
Hi @davidmr. New attributes were added for Clients: Website url, logo image, contact email and terms url. Checkout version `v0.4.0`.

**Comment by davidmr** [comment]
Awesome!, thank you very much.
