### ISSUE TITLE
Using example project only getting userinfo {"sub": "x"}

### ISSUE THREAD

**Issue by spinza** [juanifioren/django-oidc-provider#122]
How should I expand the userinfo returned by the example project.
It only returns the sub.  E.g.
```
{"sub": "3"}
```
[From this](http://django-oidc-provider.readthedocs.io/en/v0.4.x/sections/claims.html), it seems I should create a custom userinfo function but not sure where to start with this.

**Comment by juanifioren** [comment]
@spinza As I see docs are really updated. Thanks for reporting.

So basically to populate userinfo dict you must use `OIDC_USERINFO` setting.

Inside you app (called `yourproject`) create a file called `oidc_provider_settings.py` (next to your `settings.py`). Open `oidc_provider_settings.py` and create the following function:

```python
def userinfo(claims, user):

    claims['name'] = '{0} {1}'.format(user.first_name, user.last_name)
    claims['given_name'] = user.first_name
    claims['family_name'] = user.last_name
    claims['email'] = user.email

    return claims
```

Then open `yourproject/settings.py` file and add the following line:

```python
OIDC_USERINFO = 'yourproject.oidc_provider_settings.userinfo'
```

Now test an Authorization Request using these scopes `openid profile email` and see how user attributes are returned.

Greetings!

**Comment by spinza** [comment]
That worked.  The RP i'm using is expecting an 'id' field in the userinfo.  How do I add that?  Google/facebook seem to provide this typically.

I'm guessing I could make an additional scope in some way and then specify it.  Can this be done in the example without changing the library?  I'm working using your example code in the repo.

Btw. thanks for the support.

**Comment by spinza** [comment]
I think I found what I need to do:
http://django-oidc-provider.readthedocs.io/en/v0.4.x/sections/settings.html#oidc-extra-scope-claims

**Comment by juanifioren** [comment]
Yes @spinza, that's what you need.

Inside your `oidc_provider_settings.py` file add the following class:

```python
from django.utils.translation import ugettext as _
from oidc_provider.lib.claims import ScopeClaims

class CustomScopeClaims(ScopeClaims):

    info_id = (
        _(u'Identifier'),
        _(u'Access to your user identifier.'),
    )

    def scope_id(self):
        dic = {
            'id': str(self.user.id),
        }

        return dic
```

Then open `settings.py` file and add the following line:

```python
OIDC_EXTRA_SCOPE_CLAIMS = 'yourproject.oidc_provider_settings.CustomScopeClaims'
```

**Comment by juanifioren** [comment]
Hi @spinza I'll close this. Docs are now updated http://django-oidc-provider.readthedocs.io/en/v0.4.x/

If you have any question please create a new issue. Greetings!
