### ISSUE TITLE
Can I get to access the Client from a custom scope class

### ISSUE THREAD

**Issue by davidmr** [juanifioren/django-oidc-provider#128]
Right now it doesn't seem to be possible as `ScopeClaims` just stores a reference to the user and scopes as instance variables.

**Comment by juanifioren** [comment]
Hi @davidmr. What do you want to do? Maybe you can tackle it with another setting.

**Comment by davidmr** [comment]
Hi @juanifioren 

The use case goes like this: A Client (RP) can store custom data (as JSON) associated to a user via a public API call and I want to make it available as a custom claim when authenticating. The thing is that there are several RPs that want to store this custom data and I don't want them to know the custom data associated to other RPs. Because of that, when building the custom claim (containing the custom data) I need to access the Client (RP) requesting access so that I can filter out the rest of the custom data.

**Comment by davidmr** [comment]
Hi @juanifioren, I've created a small PR with what I have in mind. Thanks.

**Comment by juanifioren** [comment]
Ready in version `0.4.2`. Thanks for the contribution.
