### ISSUE TITLE
Conflicting migration detected

### ISSUE THREAD

**Issue by wojtek-fliposports** [juanifioren/django-oidc-provider#131]
With Django-oidc-provider 0.4.3 during `./manage migrate`:

`CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0020_client__post_logout_redirect_uris, 0018_auto_20161018_2043 in oidc_provider).
`

**Comment by wojtek-fliposports** [comment]
I have found two `0018`'s migrations: the wrong one is:
`/oidc_provider/migrations/0018_auto_20161018_2043.py`

if You changed name of migration file also breaks `pip install -U` command :/

**Comment by juanifioren** [comment]
Try by removing that migration. The correct one is `0018_hybridflow_and_clientattrs.py`.

**Comment by juanifioren** [comment]
I'll close this @wojtek-fliposports, if you still have this issue please reopen it.
