### ISSUE TITLE
using ugettext_lazy instead of ugettext in claims.py

### ISSUE THREAD

**Issue by pichlou** [juanifioren/django-oidc-provider#140]
I want translate authorize.html file,but using ugettext cause info_* in StandardScopeClaims not translated in template file of authorization,so i changed it to ugettext_lazy

**Comment by juanifioren** [comment]
Now is using **ugettext_lazy**. What version are you using?.

**Comment by pichlou** [comment]
Thanks !
my branch version is v 0.4.x , but claims.py was not updated!
I cloned it in 6 days ago,but your default branch updated in 4 days ago,however now  have no problem :)
