### ISSUE TITLE
How can integrate openid connect based-authentication angularjs with django-backend?

### ISSUE THREAD

**Issue by ranvijay-zymr** [juanifioren/django-oidc-provider#142]

**Comment by juanifioren** [comment]
Well you can use the implicit flow, I added [an example](http://django-oidc-provider.readthedocs.io/en/v0.4.x/sections/examples.html#pure-js-client-using-implicit-flow) of how to use OIDC with a client-side app.
You also have to validate ID_TOKEN's:
https://openid.net/specs/openid-connect-implicit-1_0.html#IDTokenValidation
If you ask for a specific library for AngularJS I can't answer that question.
