### ISSUE TITLE
refresh_token cannot be primary key if null

### ISSUE THREAD

**Issue by mjlawrence83** [juanifioren/django-oidc-provider#143]
I've just got your latest version (0.4.4) and ran a migrate but I received an error from DB2 stating that REFRESH_TOKEN cannot be a unique/primary key as it can be NULL.

I'm guessing this is just an issue because I'm using DB2. Is there potential for a fix for this?

**Comment by juanifioren** [comment]
Yes. Already push this fix on branch `v0.4.x`.

**Comment by mjlawrence83** [comment]
That's great :) do you know when you'll be pushing your next release to PyPi?

**Comment by mjlawrence83** [comment]
Hi, I've just got the latest code, I ran migrate and it still fails on the same error, I'm guessing because it's setting up with initial, and then going through each migrate script, so it still encounters the same issue on the initial script. Is there a step I'm missing?

**Comment by wojtek-fliposports** [comment]
I can't reproduce this error on MySQL, ProgreSQL and SQLite database engines.  Maybe this is DB specific bug, not related with this lib.
