### ISSUE TITLE
Support grant_type=client_credentials

### ISSUE THREAD

**Issue by orzel** [juanifioren/django-oidc-provider#153]
This is not "openid connect" strictly speaking, but a great feature of the underlying oauth2 currently not supported by django-oidc-provider

Details are 
https://tools.ietf.org/html/rfc6749#section-2.3.1
https://tools.ietf.org/html/rfc6749#section-4.4

This is especially useful when doing server-server communication through API, aka "2-legged" connection.

**Comment by thomai** [comment]
@juanifioren Do you plan to support that in the near future or do you know whether someone is working on a pull request?

**Comment by wojtek-fliposports** [comment]
This can be hard to implement, because OpenID authorizes user and OpenID Connect token is used i.e. in Django Rest Framework to log in user. Client is not a user.

In my project I have created user for Client and I am performing "Password Auth Flow" to solve this impediment.

**Comment by juanifioren** [comment]
Already supported on `develop` branch. It should be released on the next version. Any comment or test is welcome.

http://django-oidc-provider.readthedocs.io/en/develop/sections/oauth2.html#client-credentials-grant
