### ISSUE TITLE
how can access to specific user profile info in response?

### ISSUE THREAD

**Issue by pichlou** [juanifioren/django-oidc-provider#156]
i want access to specific user info with AuthorizeEndpoint,how override this or AuthorizeView for limiting response data?

**Comment by wojtek-fliposports** [comment]
I think You are asking how to get `access_token`. When You configure Client with Code Flow or Implicit Flow with `token` after authentication process you will receive `access_token` which you can use to invoke `UserProfile` endpoint and based on claims You asked for` response will have data that user gave you access to.

Reference:
Good presentation:
https://www.parisjug.org/xwiki/wiki/oldversion/download/Meeting/20150915/oidc-explained.pdf

**Comment by juanifioren** [comment]
Hi @pichlou, sorry for the late reply.
Here you can find more info of how to add user information into the response.

http://django-oidc-provider.readthedocs.io/en/v0.4.x/sections/scopesclaims.html

With the setting `OIDC_EXTRA_SCOPE_CLAIMS` you can change the behavior for each of the scopes requested.

Please feel free to ask anything (by reopening this issue) else so we can help you.

**Comment by pichlou** [comment]
Hi @juanifioren,yes i used it by tracing and reading your doc for declare new scope or override available scopes
Thanks for your reply :)
