### ISSUE TITLE
in decoding id_token with JWT (HS256/RS256) signature is invalid,which keyes are used in JWT encoding?

### ISSUE THREAD

**Issue by pichlou** [juanifioren/django-oidc-provider#157]
why JWT decoding algorithm not working on id_token in oidc-provider!?

**Comment by wojtek-fliposports** [comment]
what do you mean by `decoding algorithm` ?
Nothing in JWT is encoded (except Base64 applied on parts).
See https://jwt.io/introduction/#what-is-the-json-web-token-structure-

**Comment by wojtek-fliposports** [comment]
If you have any question please reopen ticket but in meanwhile I'm closing it.

**Comment by pichlou** [comment]
Hi @wojtek-fliposports i needed extract id_token from response object that be changed with JWT 
Thanks for your reply :)
