### ISSUE TITLE
Use "OIDC_LOGIN_URL" instead of "LOGIN_URL"

### ISSUE THREAD

**Issue by ka7eh** [juanifioren/django-oidc-provider#164]
It'd be helpful if `oidc_provider` uses `OIDC_LOGIN_URL` instead of `LOGIN_URL` for its settings.
By doing so, apps can have a different login page for their `oidc` login. The default can be `LOGIN_URL`.

**Comment by wojtek-fliposports** [comment]
I think that even better solution would be additional config parameter for client with default `OIDC_LOGIN_URL` with default `LOGIN_URL`.

What do you think about that ?

**Comment by ka7eh** [comment]
Sounds good to me. I started making changes for this one. I'll submit a PR later and we can discuss the implications.

**Comment by ka7eh** [comment]
Take a look here: https://github.com/juanifioren/django-oidc-provider/pull/166
I realized I can remove `LOGIN_URL`, because `redirect_to_login` is using it by default if no `login_url` is passed to it. What are your thoughts on it?
Also, is there any other place in the code that might be affected by this change?
