### ISSUE TITLE
Customize authorize and error templates in the settings

### ISSUE THREAD

**Issue by ka7eh** [juanifioren/django-oidc-provider#165]
Even though these two templates can be customized by overriding `oidc_provider/authorize.html` and `oidc_provider/error.html`, it adds more flexibility if their path can be set in settings.

For example a dict like this can take care of it:
```
OIDC_TEMPLATES = {
    'authorize': 'my_custom_authorize_template.html',
    'error': 'my_custom_error_template.html'
}
```

**Comment by ka7eh** [comment]
See here: https://github.com/juanifioren/django-oidc-provider/pull/167

**Comment by wojtek-fliposports** [comment]
Thanks for contribution. Please fix `try / catch / finally` block for settings section and we are ready to merge
