### ISSUE TITLE
prompt "none" is handled incorrectly when user is authenticated and consent was given

### ISSUE THREAD

**Issue by bracki** [juanifioren/django-oidc-provider#170]
According to the [spec](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) authorize with `prompt=none` can be used to check if a user is authenticated  and consent was given:

> The Authorization Server MUST NOT display any authentication or consent user interface pages. An error is returned if an End-User is not already authenticated or the Client does not have pre-configured consent for the requested Claims or does not fulfill other conditions for processing the request. The error code will typically be login_required, interaction_required, or another code defined in Section 3.1.2.6. This can be used as a method to check for existing authentication and/or consent.

This is helpful if you want to do silent login with a JavaScript client for example.
The current implementation always returns an error. Instead it should check if consent was given and then redirect successfully.

**Comment by wojtek-fliposports** [comment]
`prompt` is an OPTIONAL parameter:

> `prompt`
>     OPTIONAL. Space delimited, case sensitive list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. 

I will check how it is handled by lib.

**Comment by bracki** [comment]
Everything works as expected, my bad.
