### ISSUE TITLE
Auto-accept consent for public clients

### ISSUE THREAD

**Issue by wojtek-fliposports** [juanifioren/django-oidc-provider#175]
@juanifioren I have found your commit 3f59921
Where did you found spec that public client can't auto-accept consent ?

**Comment by juyrjola** [comment]
I read through the OpenID Connect specification as well and couldn't find any sources for this. @juanifioren: would you accept a PR removing this requirement (or at least making it configurable)? Having the consent dialog displayed every time a user logs in is not very friendly.

**Comment by wojtek-fliposports** [comment]
@juyrjola Have you checked OAuth2 specification? I could not find it either.

**Comment by wojtek-fliposports** [comment]
I think #189 solves the problem here ? @juanifioren @juyrjola @suutari-ai ?

**Comment by juyrjola** [comment]
That indeed does fix it. I believe this issue can be closed.

**Comment by suutari-ai** [comment]
Is there a new release planned from the develop branch soon?

It would be nice to have the fix from #189 released too. (Didn't understand why it wasn't merged into v0.5.x as I was hoping.)
