### ISSUE TITLE
Question: if there is plan (or already implemented) to support introspection endpoint?

### ISSUE THREAD

**Issue by Li-ReDBox** [juanifioren/django-oidc-provider#177]
This end point can be useful to a resource server to check the status of an access token. The spec: https://tools.ietf.org/html/rfc7662. Some examples of its usages: https://connect2id.com/products/server/docs/api/token-introspection.

Not sure if I have checked all sources.

**Comment by wojtek-fliposports** [comment]
Thank You for this question. 

It's a nice documentation for this end point and if you can you can create you can be part of this lib and contribute a Pull Request.

Despite that  I'm using JWT token as authentication token and protecting my microservices with it. JWT token have signature to verify, `exp` key and when you combine it with ID_TOKEN_PROCESSING_HOOK you can inject keys you need. Microservice must do some validations like signature check, expiration date, issuer and verify keys and signature (it can be done by storing this key in Redis and not ask for it for every request)

**Comment by Li-ReDBox** [comment]
Thanks for the answer. If I go this path, I will do a pull request if I think my implementation meets all the specifications.

Your JWT solution sounds interesting. Do you have any documentation or examples? When ID_TOKEN_PROCESSING is called?

**Comment by wojtek-fliposports** [comment]
OpenID Connect power is in JWT tokens (in `responce_type` called `id_token`). It can contain a lot of information about current logged user like email, is_admin or even permissions list by simply adding list of functions that injecting this data to the structure of JWT token:

http://django-oidc-provider.readthedocs.io/en/v0.4.x/sections/settings.html#oidc-idtoken-processing-hook

Here is basic information what JWT is https://jwt.io/introduction/

Here is more info: how JWT works with OpenID Connect: https://connect2id.com/learn/openid-connect

**Comment by Li-ReDBox** [comment]
Thanks for your help. I think you have answered all my questions.
