### ISSUE TITLE
TypeError at /userinfo __init__() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by osborn** [juanifioren/django-oidc-provider#192]
This is what happened when I tried to implement custom scopes as specified in the documentation. I even pasted the same code just to be sure. 

```
from django.utils.translation import ugettext as _
from oidc_provider.lib.claims import ScopeClaims

class `CustomScopeClaims(ScopeClaims):`
    info_foo = (
        _(u'Foo'),
        _(u'Some description for the scope.'),
    )

    def scope_foo(self):
        # self.user - Django user instance.
        # self.userinfo - Dict returned by OIDC_USERINFO function.
        # self.scopes - List of scopes requested.
        # self.client - Client requesting this claims.
        dic = {
            'bar': 'Something dynamic here',
        }

        return dic

    # If you want to change the description of the profile scope, you can redefine it.
    info_profile = (
        _(u'Profile'),
        _(u'Another description.'),
    )
```

**Comment by wojtek-fliposports** [comment]
Can You paste whole StackTrace ?

**Comment by osborn** [comment]
Environment:


Request Method: GET
Request URL: http://localhost:8000/userinfo

Django Version: 1.10
Python Version: 2.7.13
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'myapp',
 'oidc_provider']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'oidc_provider.middleware.SessionManagementMiddleware']



Traceback:

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/views/decorators/http.py" in inner
  40.             return func(request, *args, **kwargs)

File "/Users/osborn/code/django-oidc-provider/oidc_provider/lib/utils/oauth2.py" in view_wrapper
  60.             return view(request,  *args, **kwargs)

File "/Users/osborn/code/django-oidc-provider/oidc_provider/views.py" in userinfo
  193.     standard_claims = StandardScopeClaims(token)

File "/Users/osborn/code/django-oidc-provider/oidc_provider/lib/claims.py" in __init__
  22.         self.userinfo = settings.get('OIDC_USERINFO')(claims, self.user)

Exception Type: TypeError at /userinfo
Exception Value: __init__() takes exactly 2 arguments (3 given)

**Comment by wojtek-fliposports** [comment]
What is your `'OIDC_USERINFO'` setting value ?

**Comment by osborn** [comment]
`'myapp.oidc_provider_settings.CustomScopeClaims'`

I keep the oidc_provider_settings.py file in the app.

**Comment by wojtek-fliposports** [comment]
Ok. This a BUG in documentation.
Instead of `OIDC_USERINFO` you should change `OIDC_EXTRA_SCOPE_CLAIMS` setting.

**Comment by osborn** [comment]
Ok. Thank you very much. You saved my day!
