### ISSUE TITLE
Shouldn't scope claims be included in the id_token if it's the only thing asked in the response_type

### ISSUE THREAD

**Issue by dedsm** [juanifioren/django-oidc-provider#209]
If I understand correctly, the when using response_type=id_token, all claims belonging to the requested scopes should be included in the id_token payload.

**Comment by wojtek-fliposports** [comment]
Do You have any spec for that?

**Comment by dedsm** [comment]
no, can't find anything other than the id_token MAY include more claims, but it'd be a nice to have IMHO

**Comment by juanifioren** [comment]
Already on `develop`. Next version will contains this feature. Thanks for reporting @dedsm.

http://django-oidc-provider.readthedocs.io/en/develop/sections/settings.html#oidc-idtoken-include-claims
