### ISSUE TITLE
Internal Server Error: /openid/callback/login/ 

### ISSUE THREAD

**Issue by Allan-Nava** [juanifioren/django-oidc-provider#217]
I have got this error:

> Internal Server Error: /openid/callback/login/
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
>     response = self._get_response(request)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/djangooidc/views.py", line 91, in authz_cb
>     login(request, user)
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/__init__.py", line 139, in login
>     request.session.cycle_key()
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/base.py", line 311, in cycle_key
>     self.create()
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/db.py", line 54, in create
>     self.save(must_create=True)
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/db.py", line 83, in save
>     obj = self.create_model_instance(data)
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/db.py", line 69, in create_model_instance
>     session_data=self.encode(data),
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/base.py", line 98, in encode
>     serialized = self.serializer().dumps(session_dict)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/signing.py", line 93, in dumps
>     return json.dumps(obj, separators=(',', ':')).encode('latin-1')
>   File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
>     **kw).encode(obj)
>   File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>   File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
>     return _iterencode(o, 0)
>   File "/usr/lib/python3.5/json/encoder.py", line 179, in default
>     raise TypeError(repr(o) + " is not JSON serializable")
> TypeError: <oic.oic.message.AddressClaim object at 0x7fe8c7626cc0> is not JSON serializable
> ERROR:django.request:Internal Server Error: /openid/callback/login/
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
>     response = self._get_response(request)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/djangooidc/views.py", line 91, in authz_cb
>     login(request, user)
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/__init__.py", line 139, in login
>     request.session.cycle_key()
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/base.py", line 311, in cycle_key
>     self.create()
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/db.py", line 54, in create
>     self.save(must_create=True)
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/db.py", line 83, in save
>     obj = self.create_model_instance(data)
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/db.py", line 69, in create_model_instance
>     session_data=self.encode(data),
>   File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/base.py", line 98, in encode
>     serialized = self.serializer().dumps(session_dict)
>   File "/usr/local/lib/python3.5/dist-packages/django/core/signing.py", line 93, in dumps
>     return json.dumps(obj, separators=(',', ':')).encode('latin-1')
>   File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
>     **kw).encode(obj)
>   File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>   File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
>     return _iterencode(o, 0)
>   File "/usr/lib/python3.5/json/encoder.py", line 179, in default
>     raise TypeError(repr(o) + " is not JSON serializable")
> TypeError: <oic.oic.message.AddressClaim object at 0x7fe8c7626cc0> is not JSON serializable
> [04/Dec/2017 08:43:12] "GET /openid/callback/login/?state=TeCCDOSWCHOUVWRA&code=PwLo-eO_5rJMWkaO9y0PzQjuH5DNACuRvXvWcxPV2t4.ef76031f-094c-4e55-b8e1-f217522b4ecc HTTP/1.1" 500 156069
>

**Comment by dhrp** [comment]
Check that your 'address' claim is valid. In your output I can see:

TypeError: <oic.oic.message.AddressClaim object at 0x7fe8c7626cc0> is not JSON serializable

**Comment by Allan-Nava** [comment]
@dhrp How can I fix this error?

**Comment by dhrp** [comment]
Take a good look at your address claim. Possibly it contains objects that are not JSON serializable. Try to json.loads() your body manually. Possibly you can also just not ask for the address scope in your request.

**Comment by Allan-Nava** [comment]
Ok thanks!

2018-01-19 11:07 GMT+01:00 Thatcher <notifications@github.com>:

**Comment by dhrp** [comment]
Go ahead and close this issue if you've solved your problem.
