### ISSUE TITLE
Django 2.0: 'bool' object is not callable is_authenticated

### ISSUE THREAD

**Issue by timatooth** [juanifioren/django-oidc-provider#218]
Field is not callable as a method anymore in Django 2.0
in `oidc_provider/views.py`

https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated
> In older versions, this was a method. Backwards-compatibility support for using it as a method will be removed in Django 2.0.

Looks like this was changed in 1.10 so should support for prior versions be dropped?

**Comment by wojtek-fliposports** [comment]
I think @juanifioren need to make decision about dropping version support

**Comment by suutari-ai** [comment]
Why not just write a simple wrapper like the following so that backwards compatibility wouldn't be any issue? (Nor it wouldn't matter which Django version changed it)

```python
def is_authenticated(user):
    if callable(user.is_authenticated):
        return user.is_authenticated()
    return user.is_authenticated
```

**Comment by reinout** [comment]
Pull request #216 fixes this.

**Comment by wojtek-fliposports** [comment]
merged
