### ISSUE TITLE
Allow auto-consent for authorisation code flow as well.

### ISSUE THREAD

**Issue by dhrp** [juanifioren/django-oidc-provider#222]
I have used several other libraries for oAuth, but have not before seen the limitation that public clients with an authorisation grant flow MAY NOT auto-approve consent. 

In my use-case I am using two different applications, that we ourselves develop and use oAuth for that (public authorisation code flow). We don't want our users to have to consent every time, I could also not find it in the spec.. Hardcoding it in the library therefore seems inappropriate. 

I have found #189 (which doesn't do what I need, it's only for implicit flow) 
and 
#175 which discusses this, but that issue was closed.

I think the developer should allow to choose to allow this on a per-client basis. If the developer would make it possible to self-request an oAuth client THEN the developer can disable the auto-consent there.

**Comment by dhrp** [comment]
I'd be happy to make a PR for this..

**Comment by OmenApps** [comment]
Isn't this fixed in [Adds per-client consent customization](https://github.com/juanifioren/django-oidc-provider/commit/b164388e15b8edc46e0ded28ca8d2056051caee7#diff-76399cf8cc3acfac723da8fecc5be309)?

@juanifioren - this old issue could probably be closed now
