### ISSUE TITLE
What Client library to use with DOP and Django

### ISSUE THREAD

**Issue by harwee** [juanifioren/django-oidc-provider#223]
I was wondering what django-app/library is being used to make a django oidc client. I am facing issue with private client authorization, can anyone point me to a source to read about private client authorization with django

**Comment by montudor** [comment]
[mozilla-django-oidc](https://github.com/mozilla/mozilla-django-oidc) may be useful to you for this purpose.

**Comment by harwee** [comment]
I have looked into it, but the License makes it difficult to use with my project, I ended up starting to write the implementation from scratch as i didn't find any other library which is being maintained.

**Comment by juanifioren** [comment]
@harwee use http://python-social-auth.readthedocs.io/en/latest/
