### ISSUE TITLE
manage.py not found

### ISSUE THREAD

**Issue by karimcse** [juanifioren/django-oidc-provider#235]
I am newbie to python django.
I cannot find manage.py in full repository.
Please help for running this django project

**Comment by juanifioren** [comment]
Hi @karimcse, the project is a Django package so there's no need for a `manage.py` file (that's for apps). Check out example folder [here](https://github.com/juanifioren/django-oidc-provider/tree/v0.5.x/example_project#manually). Please ask me if you have another question.
