### ISSUE TITLE
Scopes in concent/authorization

### ISSUE THREAD

**Issue by toti1212** [juanifioren/django-oidc-provider#239]
Hi Juni,

I don't understand something about scopes and authentication endpoint.
When the user accept the concent, are in the url all the scopes that accept? What happen if I can handle the url, adding more scopes? I can see that the template render the scopes that read in the params, but.. the user can manipulate it?

Its a good aproach only send the `openid` scope and get the others from the Client model?

Thanks!

**Comment by juanifioren** [comment]
Hola Rodrigo.

Yes! the package extract scopes from URL, but only those who are registered on the Provider will be printed on the consent template. So if the user manipulate the url there are two possible scenarios:

- Adding more scopes: no undesirable effects here, if extra scopes are not registered by the Provider. If they are, the user will see them and approve the consent.
-  Removing some scopes: this have undesirable effects for the Client app, but this is the same as for example in Facebook consent when user restrict some info, like email or phone. Client SHOULD validate data after getting info from userinfo endpoint.

**Its a good aproach only send the openid scope and get the others from the Client model?**
No problem with this, but we try to attach to the protocol.

Greetings!

**Comment by toti1212** [comment]
Thanks!
