### ISSUE TITLE
Issue| request object is not sent in authenticate

### ISSUE THREAD

**Issue by ahmedhosnycs** [juanifioren/django-oidc-provider#240]
I see `TokenEndpoint` class in `oidc_provider/lib/endpoints/token.py` is calling authenticate method incorrectly.
```
user = authenticate(
    username=self.params['username'],
    password=self.params['password']
)
```

without `request` parameter. I do believe that sending it like:
```
user = authenticate(
    request=self.request,
    username=self.params['username'],
    password=self.params['password']
)
```

will help me for add further functionalities by overriding the `authenticate` method only.

**Comment by q3aiml** [comment]
I found this useful too and have a PR open #221

**Comment by ahmedhosnycs** [comment]
@q3aiml is it now 7 months for PR to be reviewed and merged?

**Comment by juanifioren** [comment]
Merged into `develop`. Thanks for reporting.
