### ISSUE TITLE
Question: Combining OIDC provider with REST Framework

### ISSUE THREAD

**Issue by ggjersund** [juanifioren/django-oidc-provider#242]
Is there a way to combine this provider with Django REST framework? Or does OIDC Provider come with an authentication backend middleware?

I want to be able to simply accept the access token on my API and extract the user information (same database) from it. I've tried reading through the code, and the docs, however, I couldn't seem to find any information about this.

TLDR; I have a resource server and this provider running in the same Django Project. Can I check the access tokens sent to the API as a middleware?

**Comment by juanifioren** [comment]
DUPLICATE. SEE https://github.com/juanifioren/django-oidc-provider/issues/78

Hi @ggjersund. This is a feature we want to add. Here it's some code created by @koriaf about an integration with DRF.

https://gist.github.com/koriaf/907d1e16068d1a04056eedf736a203f5

**Comment by ggjersund** [comment]
@juanifioren Does this work for all the token types? or just bearer?

**Comment by wojtek-fliposports** [comment]
I'm using own Auth class to validate OpenID Connect JWT tokens in DRF. I will try to PR with authentication DRF class. One question to @juanifioren does scopes are included inside token in the latest version of this lib?
If not, I will also provide ID_TOKEN processing hook to inject scopes inside token

**Comment by suutari-ai** [comment]
@wojtek-fliposports Do you mean like in PR #194?

**Comment by OmenApps** [comment]
@ggjersund - Does #342 help?
