### ISSUE TITLE
[Q] Scopes accepted as user and scopes saved in models (client, userconsent, token). 

### ISSUE THREAD

**Issue by toti1212** [juanifioren/django-oidc-provider#244]
Hi.

As a User, I can accept concent that involves a list of scopes that Client doest have in their model.(client._scope), the package create a instance of Authorization Code that have that list. So, in the userinfo i can get that information? 

I my code check that user consent save the intersection between Client scope and URL scopes.
you did not do it for something? or am I wrong?

**Comment by juanifioren** [comment]
Hi @toti1212, nice question. But this is just a misunderstood. `Client.scope` is used by the Client Credentials Grant (an OAuth2 feature), which enables client to request an access token using only its client credentials (removing user in the flow).

Read more on docs: http://django-oidc-provider.readthedocs.io/en/develop/sections/oauth2.html#client-credentials-grant

**Comment by juanifioren** [comment]
@toti1212 Please let me know if I answer your doubt.

**Comment by juanifioren** [comment]
@ggjersund Random example: You want to expose an API that shows how much users loggued in some specific Client. Then Client use that endpoint to access that information. Using client credentials grant would access only the number that belongs to it. Users can't access, neither other clients.
