### ISSUE TITLE
Scopes are not found if a Claims class is inherited further

### ISSUE THREAD

**Issue by mikkokeskinen** [juanifioren/django-oidc-provider#247]
We had a case where we needed to change StandardScopeClaims only a little. We then created a new class and added StandardScopeClaims as a base class. Like
```py
    class CustomStandardScopeClaims(StandardScopeClaims):
        def scope_profile(self):
            # Something
```
The result was that the other scopes were not found any more. That is because in https://github.com/juanifioren/django-oidc-provider/blob/master/oidc_provider/lib/claims.py#L71 the scope names are searched from the classes using `__dict__` which of course doesn't include inherited attributes or methods. (Same thing with the `get_scopes_info`)

I'd say the better way would be to use `dir`. e.g.
```py
    for name in dir(self.__class__):
```
and
```py
    for name in dir(cls):
```

What do you think?

**Comment by juanifioren** [comment]
Fix released on `v0.6.2`.
