### ISSUE TITLE
Question: Can I have scopes without claims?

### ISSUE THREAD

**Issue by ggjersund** [juanifioren/django-oidc-provider#248]
I'm wondering if I can use scopes without claims in the case described [here](http://django-oidc-provider.readthedocs.io/en/latest/sections/scopesclaims.html#how-to-add-custom-scopes-and-claims). Or is this considered bad practice?

I want to use scope to give access to my API, but I dont wish to return anything for the specified scope in the `/userinfo` url. Is this valid? or is it the actual way scopes are intended to be used most of the time?

**Comment by ggjersund** [comment]
Also, is there a hook for returning an error if a client makes a request to a scope, but the user hasn't consented to a policy concerning this scope? Wondering due to the new privacy laws in effect, and I need users to consent to scopes individually to make it possible to manage individual parts of my API.

**Comment by juanifioren** [comment]
Hi @ggjersund 
*1st question* 
Yes you can! just return empty `{}`. Is a valid usage.
*2nd question*
That is out of the scope of openid, and can be implemented appart. Fox example when user clicks "accept policy" you store `user, scopes, date, etc` then you can use [OIDC_AFTER_USERLOGIN_HOOK](http://django-oidc-provider.readthedocs.io/en/develop/sections/settings.html#oidc-after-userlogin-hook) to check if the user accept that scopes.

Any other question please ask! Thanks.

**Comment by juanifioren** [comment]
Remember this when using OIDC_AFTER_USERLOGIN_HOOK

> The typical situation will be checking some state of the user or maybe redirect him somewhere. With request you have access to all OIDC parameters. Remember that if you redirect the user to another place then you need to take him back to the authorize endpoint (use request.get_full_path() as the value for a “next” parameter).

**Comment by ggjersund** [comment]
@juanifioren However, what if the policy is updated, but the user is still logged in? or is the user login referencing to client login?

**Comment by ggjersund** [comment]
@juanifioren I would have that as well, but does `OIDC_AFTER_USERLOGIN_HOOK` reference to client login (e.g click to login with Facebook and redirect back) or provider login (e.g login to Facebook before authorizing and redirecting)?

**Comment by juanifioren** [comment]
It happens between user logs in and showing OpenID authorization.
