### ISSUE TITLE
User association with client credentials flow

### ISSUE THREAD

**Issue by brianorwhatever** [juanifioren/django-oidc-provider#250]
I want to use the client_credentials flow to allow server to server authentication with an API. My api will receive the access token and send it to my oidc server's userinfo endpoint. This currently results in a 500 because there is no user associated with that token. I would like to create a 1 to 1 relationship between these types of clients and users (using the owner field). Is it possible to add this functionality or is it complete breaking the spec?

**Comment by juanifioren** [comment]
Hi @brianorwhatever, client credentials flow is intended for use in machine-to-machine authentication. Yes, this will break the spec for userinfo endpoint. You can still create your own service and use credential grant.

Read more: http://django-oidc-provider.readthedocs.io/en/latest/sections/oauth2.html#protecting-views

**Comment by brianorwhatever** [comment]
I believe the token introspection endpoint is what I am looking for which was merged into develop in April https://github.com/juanifioren/django-oidc-provider/pull/231
Any idea when you might release this?

**Comment by q3aiml** [comment]
Token introspection endpoint currently relies on id_token and also 500s with access tokens generated from client credentials grant

**Comment by juanifioren** [comment]
@q3aiml Sorry, but client credentials grant is not intended for authentication mechanisms. Since you are leaving the user out of the flow. I don't get your point.

**Comment by q3aiml** [comment]
I agree with you when you said earlier that client credentials flow is for machine-to-machine authentication. Can you help me understand what you are now saying? I am reading it as the exact opposite of that earlier statement.

What we would like to do is machine-to-machine authentication where the resource server and authorization server are separate and do not share the django-oidc-provider database:
1. Machine client retrieves access token from authorization server running django-oidc-provider
2. Machine client makes request to resource server using access token
3. Resource server validates access token with authorization server -- don't think this is currently possible with django-oidc-provider

**Comment by q3aiml** [comment]
@juanifioren have you had any thoughts about this and increasing the usability of client credentials grant? Would you prefer I open a different, broader issue and move the discussion there?

**Comment by juanifioren** [comment]
@q3aiml please, let's discuss what the best for this

**Comment by q3aiml** [comment]
@juanifioren thanks so much for being open and spending your time to talk about this. I opened #256 as an example of how introspection could support client credentials tokens. It isn't perfect but hopefully it gives a clearer idea what I am thinking. Let me know what you think
