### ISSUE TITLE
Token Model crashes in Django Admin when a token has been given to a Client using Client Credentials

### ISSUE THREAD

**Issue by boris900305** [juanifioren/django-oidc-provider#253]
When a client request a token using client credentials, this is token is created with no user id associated, so in models.py, on line 152, when it tries to access self.user.email, it crashes because there is no associated user. It can be easily fixed with an if, to check first. For example:
`def __str__(self):
        return u'{0} - {1}'.format(self.client, self.user.email if self.user else self.client.contact_email)`

**Comment by juanifioren** [comment]
Fix d825061508b485310c601844b6ecbe47f7c9721d

Thanks for reporting @boris900305
