### ISSUE TITLE
Add support for Django 2.1

### ISSUE THREAD

**Issue by dcollinsn** [juanifioren/django-oidc-provider#258]
Greetings,

Django 2.1 (currently available as django==2.1rc1 in pip) deprecates the function based views in django.contrib.auth.views. oidc_provider.views' EndSessionView will need to be refactored to subclass the newer LogoutView, which is probably fairly straightforward since your view is already a class-based view.

LogoutView was new in Django 1.11. I don't know whether you want to continue supporting 1.10 or not.

**Comment by juanifioren** [comment]
Thanks, yes we should start adding 2.1 into tests. I think dropping 1.10 and lower shouldn't be a bad decision.
