### ISSUE TITLE
code is not zip safe

### ISSUE THREAD

**Issue by stdweird** [juanifioren/django-oidc-provider#262]
code is not zip safe, and setuptools seems to misdetect it.

fix is as simple as adding `zip_safe = False,` to setup.py

issue we have is the following:
when adding `django-oidc-provider` to the `install_requires` of another django project, running the test of that project `django-oidc-provider` is installed as a zipped egg, and then the tests fail with
```
error: [Errno 20] Not a directory: '/var/lib/jenkins/jobs/<snip>/branches/PR-1036/workspace/.eggs/django_oidc_provider-0.6.1-py2.7.egg/oidc_provider/migrations'
```

**Comment by juanifioren** [comment]
Thanks for contributing @stdweird
