### ISSUE TITLE
Client Registration Endpoint

### ISSUE THREAD

**Issue by happy-dev** [juanifioren/django-oidc-provider#263]
Hi guys, 

Is [this spec](https://openid.net/specs/openid-connect-registration-1_0.html) implemented by the lib ? 
If it is, could you tell me the URI of the `Client Registration Endpoint` ?

All the best !

**Comment by jblemee** [comment]
Hi,

See : https://github.com/juanifioren/django-oidc-provider/issues/59

And one implementation in this fork :https://github.com/wayward710/django-oidc-provider/commits/v0.2.x

**Comment by juanifioren** [comment]
Hi, is currently not! closing because of duplicate.
