### ISSUE TITLE
Set allowed response_types by grant.

### ISSUE THREAD

**Issue by HauptmannEck** [juanifioren/django-oidc-provider#270]
In Identity Server there is the ability to have a client support multiple response_type's through setting an Allowed Grant (Implicit, Hybrid, ClientCredentials). This allows a Client to support both `id_token` and `id_token token`.

This is functionality that is used by `oidc-client-js` to get a simplified session status response.

Would this be something `django-oidc-provider` would support? or is there a workaround to allow 1 client 2 response_types?

**Comment by juanifioren** [comment]
To be released on `v0.6.3`. Thanks @HauptmannEck for reporting and @q3aiml for the MR.
