### ISSUE TITLE
How to handle scope updates ?

### ISSUE THREAD

**Issue by Amoki** [juanifioren/django-oidc-provider#276]
The table `UserConsent` doesn't remember (unlike the North) the scopes validated by end users. If a user allows a scope of a client and then the client is updated with more scopes, is the client able to use these new scopes ?
Should I manually delete `UserConsent` rows with this client and force the logout of affected users to force a new /authorize ?

**Comment by suutari-ai** [comment]
Actually `UserConsent` inherits from `BaseCodeTokenModel` which has a `_scope` (text)field (and a `scope` property to access its value). Though, I don't remember if the scopes are actually being checked when checking the consent for reuse.

**Comment by Amoki** [comment]
Oh thanks, I missed that. So the `UserConsent` remembers.!
