### ISSUE TITLE
Make AuthorizationBackend and Client more easily adjustable

### ISSUE THREAD

**Issue by kerrermanisNL** [juanifioren/django-oidc-provider#278]
Previously PR https://github.com/juanifioren/django-oidc-provider/pull/163 removed the settings for skipping consent. Instead the functionality was moved to the `Client` model, but it's quite hard to make changes to make sure custom `Clients` are used. So it would be nice to introduce some functionality that would improve this. I know it would be possible to make the change on the actual `Client` entry in the database, but this is obscure and not easily visible for other developers. I'd rather have some explicit model define this change instead.

PR incoming that should make this stuff a little easier to manage.

**Comment by kerrermanisNL** [comment]
Hm, I just realised that seeing it in the admin is probably explicit enough. Kind of a fail on my part :smirk: I still think the PR could prove useful though. I'll let you guys decide what to do with it.

**Comment by juanifioren** [comment]
I think per-client edition on admin is quite good for the moment. Also that the logic should be on Client model (not another one). Thanks @kerrermanisNL

**Comment by kerrermanisNL** [comment]
Yeah I agree. Somehow the admin stuff just hadn't occurred to me :+1:
