### ISSUE TITLE
bug in strip_prompt_login

### ISSUE THREAD

**Issue by stdweird** [juanifioren/django-oidc-provider#283]
we have an url that ends with `&prompt=login%20consent` that is passed to authorize view.
the query_params https://github.com/juanifioren/django-oidc-provider/blob/master/oidc_provider/views.py#L209 has `u'prompt': [u'login consent']`
but then the code that follows treats this as a list, which fails and cause redirects (or some loop or whatever).

looks like a `.split()` is missing (similar to the split used in https://github.com/juanifioren/django-oidc-provider/blob/master/oidc_provider/lib/endpoints/authorize.py#L81)

**Comment by kitab15** [comment]
Hi @stdweird we ran into a similar problem some time ago, and we fix it adding a `.split()` as follows:

```
def strip_prompt_login(path):
    """
    Strips 'login' from the 'prompt' query parameter.
    """
    uri = urlsplit(path)
    query_params = parse_qs(uri.query)
    prompt_list = query_params.get('prompt', '')[0].split()
    if 'login' in prompt_list:
        prompt_list.remove('login')
        query_params['prompt'] = prompt_list
    if not query_params['prompt']:
        del query_params['prompt']
    uri = uri._replace(query=urlencode(query_params, doseq=True))
    return urlunsplit(uri)
```

if @juanifioren agree I can make a PR with the change.

**Comment by juanifioren** [comment]
Hi @kitab15, please! go ahead.
