### ISSUE TITLE
Add support of method for access control between user and client

### ISSUE THREAD

**Issue by vitalvas** [juanifioren/django-oidc-provider#284]
We need a mechanism to control where the customer can enter.

Examples:
- Grafana - only employees and partners
- VPN - only employees
- Billing - all users
- Some product - only beta testers.

I think - add to user model new method:
```
class CustomUser(AbstractUser):
    ....
    def has_oidc_access(self, oidc_client):
        #  oidc_client - Client object
        if ....:
            return False # deny authorize
        return True # allow authorize
```

**Comment by juanifioren** [comment]
Hi @vitalvas, you can use [OIDC_AFTER_USERLOGIN_HOOK](https://django-oidc-provider.readthedocs.io/en/latest/sections/settings.html#oidc-after-userlogin-hook) to stop before authorize view.

```
def default_hook_func(request, user, client):
    if ....:
        return render('you_cant_enter_here.html') # deny authorize
```

**Comment by vitalvas** [comment]
It worked. Thank you.
