### ISSUE TITLE
Redirect URI Error?

### ISSUE THREAD

**Issue by rsung** [juanifioren/django-oidc-provider#29]
Hi, 

I'm using the same project and getting "Redirect URI Error" when submitting the following request.

http://localhost:8000/openid/authorize/?client_id=123&scope=openid&state=766841&redirect_uri=https://www.getpostman.com/oauth2/callback&response_type=code

redirect_uri is present in the query string. please advise.

**Comment by juanifioren** [comment]
Hi @rsung,

Please ensure that your `oidc_provider.models.Client` object has the same uri that you send in the auth request.

Just `python manage.py shell` and:
```python
from oidc_provider.models import Client
client = Client.objects.get(client_id='123')
client.redirect_uris
```

Please let me know how it was!

_-Ignacio_

**Comment by rsung** [comment]
Yes, I was just looking into that.  Sorry, I should have done more research before raising a flag.  Thanks!

**Comment by juanifioren** [comment]
No problem! Sometimes happens! haha

_-Ignacio_
