### ISSUE TITLE
Redirecting to URL with no query parameters but as anchor `#`

### ISSUE THREAD

**Issue by harwee** [juanifioren/django-oidc-provider#319]
I have a client trying to authorize. the client gets redirected to login page, but after authentication the server redirects back to the callback url but it doesn't contain query params, well there are params but are not separated using `?` but with `#` this is the url the server is redirecting to 

        http://localhost:4200/#access_token=<access__token>&id_token=<id_token>&token_type=bearer&expires_in=300&state=15555959783820.46818024069401387&session_state=7cf4ef8b55b1c93ddcb63ef63f2b70a25c9b2679af5e43b4176887227e2d84a8.d4fe517df163156c064ddbc7f2017196

This is the request to the server

        /oidc/authorize?client_id=709345&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&response_type=id_token%20token&scope=openid&nonce=N0.50879187872710061555594711850&state=15555959783820.46818024069401387

**Comment by Amoki** [comment]
IIRC this is the indented behavior.
You can find an example to deal with these params here: https://openid.net/specs/openid-connect-core-1_0.html#FragmentNotes

**Comment by harwee** [comment]
Oh ok mybad, I think the problem I am facing is not because of this then. I will close this issue
