### ISSUE TITLE
Tests fail because of changes in flake8

### ISSUE THREAD

**Issue by zvyn** [juanifioren/django-oidc-provider#322]
Options to solve this:
1. Ignore `W605 invalid escape sequence` errors and pin flake8 to the current version
2. Fix the `W605 invalid escape sequence` errors and pin flake8 to the current version
3. Pin flake8 to the last version that worked

I am happy to provide a PR, just let me know which solution you prefer.

**Comment by juanifioren** [comment]
Hi @zvyn maybe 2. will be better, what do u think?

**Comment by zvyn** [comment]
Sorry for the noise, I branched off of master at first and had to rebase. Doing that I found out that there was nothing left to do but to pin flake8. Anyway: I made a PR to develop now: #323
