### ISSUE TITLE
Handle optional scope on token and introspection endpoints for password and client_credentials grant_type

### ISSUE THREAD

**Issue by EvgeniGordeev** [juanifioren/django-oidc-provider#328]
Parameter scope is defined as optional on authorization https://tools.ietf.org/html/rfc6749#section-4.1.1 and introspection https://tools.ietf.org/html/rfc7662 requests. 

An enhancement is proposed to handle `scope` parameter on authorization requests with grant_type=password or grant_type= client_credentials (related to https://github.com/juanifioren/django-oidc-provider/pull/193):
1) if `scope` is not provided client's scope(s) are assigned to access token - 

- grant_type=client_credentials: current behavior of django-oidc-provider
- grant_type=password: currently django-oidc-provider assigns empty scope

2) if valid (supported by given client) scopes are requested requested scopes are assigned to access token
3) if requested scope(s) are not supported `raise TokenError('invalid_scope')`

An enhancement is proposed to display optional `scope` in introspection response controlled by new settings variable `OIDC_INTROSPECTION_RESPONSE_SCOPE_ENABLE`.

**Comment by juanifioren** [comment]
Merged!
