### ISSUE TITLE
Error when migrating on production server with postgresql

### ISSUE THREAD

**Issue by ggjersund** [juanifioren/django-oidc-provider#334]
Having problem migrating this library on the production server using postgresql.

```
Applying oidc_provider.0004_remove_userinfo...Traceback (most recent call last):
  File "/home/user/virtualenv/api/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.SyntaxError: syntax error at or near "WITH ORDINALITY"
LINE 6:                     FROM unnest(c.conkey) WITH ORDINALITY co...
```

**Comment by ggjersund** [comment]
Possible solution:
I suspect its related to my hosting providers version of postgresql.
[https://docs.djangoproject.com/en/2.1/releases/2.1/#dropped-support-for-postgresql-9-3](https://docs.djangoproject.com/en/2.1/releases/2.1/#dropped-support-for-postgresql-9-3)

**Comment by florian-hartmann** [comment]
If you are using Django >= 2.1 and Postgres <= 9.3 then this is not an issue with the `django-oidc-provider` extension and we should close this issue.

**Comment by ggjersund** [comment]
It was related to postgresql version and Django version. Closing the issue.
