### ISSUE TITLE
Internal Server Error: /openid/callback/login/ 

### ISSUE THREAD

**Issue by afrida67** [juanifioren/django-oidc-provider#338]
I'm getting this error after I logged into my secured page 

`
/home/afrida/.local/lib/python3.6/site-packages/django/core/handlers/exception.py in inner
            response = get_response(request) ...
▶ Local vars
/home/afrida/.local/lib/python3.6/site-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/home/afrida/.local/lib/python3.6/site-packages/django/core/handlers/base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/home/afrida/.local/lib/python3.6/site-packages/djangooidc/views.py in authz_cb
`
And also if I reload then a new error occurs:
```
OpenID Connect authentication has failed
Error message is: Invalid response invalid_grant.
```

This is my settings.py

```
auth_uri = "http://localhost:8080/auth/realms/test"
client_id = "test"
public_uri = "http://localhost:8000"
scope = ['openid', 'profile', 'email'] 

from bossoidc.settings import *

configure_oidc(auth_uri, client_id, public_uri, scope)
OIDC_PROVIDERS['KeyCloak']['behaviour']['scope'] = ['openid', 'profile', 'email']
```
I'm using keycloak server auth

**Comment by karambir** [comment]
Hi @afrida67 this is wrong project for you to report your issue. I believe you are using "django-oidc" and not "django-oidc-provider"(this project). Please report here https://github.com/marcanpilami/django-oidc
