### ISSUE TITLE
Access token validation

### ISSUE THREAD

**Issue by rsung** [juanifioren/django-oidc-provider#35]
From resource server (RS), is there a way to validate the access token?

Thanks,
-r

**Comment by juanifioren** [comment]
Hi @rsung,

You mean something like [this](https://developers.google.com/identity/protocols/OAuth2UserAgent#tokeninfo-validation)?.

**Comment by rsung** [comment]
Thanks @juanifioren. I was actually thinking of the one like the Google API offers.

I was also looking for a token revocation endpoint.  Looking at the 0.1.0-dev branch, it looks like it's not being planned as well.

I need these for my project.  If you're interested, I can implement them and send you a pull request.

Please let me know.

**Comment by juanifioren** [comment]
Hi,

The _"TokenInfo"_ that google have is useful for debugging (involves an HTTP round trip) but for production purposes, is recommended that you retrieve server public keys from the keys endpoint and perform the validation manually. Thats why RSA sign is priority now. I'll like to contact you in a future to see how you make it works, thanks @rsung.

Greetings.

**Comment by juanifioren** [comment]
Check out version `v0.1.0`.
