### ISSUE TITLE
Log level severity is set too low

### ISSUE THREAD

**Issue by sidagrawal** [juanifioren/django-oidc-provider#353]
This library is really great for integrating OAuth into a django app. Unfortuantely, I'm having a bit of trouble with my logs because the log severity on the authorize endpoint is set to DEBUG. These errors are ones that I would like to catch but turning on DEBUG level logs in a production environment will lead to way too many logs. I think it would make more sense to have these logs be at the error level or perhaps have some method to set the log severity level to different levels based on need. Please let me know what you think, thanks!

**Comment by geoff-va** [comment]
You could set the log level to `DEBUG` specifically for the `oidc_provider` app in your django `settings.py` file?

**Comment by sidagrawal** [comment]
I'm not sure how to set the log level for a specific package in the `settings.py` file. Could you point me in the right direction?

**Comment by geoff-va** [comment]
You can follow the patterns [here](https://docs.djangoproject.com/en/2.2/topics/logging/#examples).

Something like the following:

```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'debug_console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'oidc_provider': {
            'handlers': ['debug_console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    }
}
```

**Comment by geoff-va** [comment]
@sidagrawal can you close this if it solves your problem?

Thanks!

**Comment by sidagrawal** [comment]
Thanks for solving this!
