### ISSUE TITLE
Pairing Social login

### ISSUE THREAD

**Issue by alexander-arce** [juanifioren/django-oidc-provider#360]
Hi everyone,
Any one has added social login capabilities along oidc-provider ?.
A requiremente in project is decouple login,autentication, autorizathion as a microservice.

What's steps is needed to add social login with oidc-provider ?
Thanks

**Comment by juanifioren** [comment]
@alexander-arce on your login screen you can use any method to authenticate your users, so this is not part of the scope of the OpenID Connect implementation. I recommend you [allauth](https://docs.allauth.org/)
