### ISSUE TITLE
Can I use Github third party authentication  for login !

### ISSUE THREAD

**Issue by praveenbommalibits** [juanifioren/django-oidc-provider#371]
Hi 
Where can I  do the customisation  to support the third party authentication like GitHub or Google or Okta ...etc. 
In order to achieve that where I can change the files.

**Comment by juanifioren** [comment]
OIDC is not handling how you identify your users, so you can use any login system you want. Use Django login url to send the user to your custom login view. Then redirect back to the starting url.
