### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by variable** [juanifioren/django-oidc-provider#377]
Hello Given last commit was 2 years ago, is this project still being maintained? If not, what is the alternative?

**Comment by suutari-ai** [comment]
I don't know how actively this project is maintained, but the presumption in the question is wrong. There are newer commits than two years on the develop branch, latest from Dec 2020 currently: https://github.com/juanifioren/django-oidc-provider/commits/develop

@juanifioren Would you care to share any update regarding the maintenance status of the project? There seems to some good looking PRs in the queue, any plans to merge any of them and release a new version? (at least #361 seems trivial to review, but pretty important)

**Comment by rh0dium** [comment]
Does anyone want to volunteer as a maintainer?  If we can identify a person then we can reach out to @juanifioren with a potential replacement. This is used by a number of folks and it would be nice to get upstream support.  Alternatively are there any active forks that people use instead. 

For me the number of DjangoWarnings is getting heavy - I'll gladly do a PR but we need someone to merge this stuff.

**Comment by dmptrluke** [comment]
I believe maintaining this project is important. I noticed quite heavy feature/documentation changes on the various branches of https://github.com/catalyst/django-oidc-provider last year, but that has stopped for now.

There doesn't seem to be any one upstream where someone is keeping track of things and managing pulls/etc. @juanifioren has accepted a few here in the last year, but also ignored security fixes, so I think it is clear that things are not happening.

**Comment by OmenApps** [comment]
If @juanifioren will accept maintainers, I would be willing to put in some time long-term with administrative aspects of maintenance (adding some basic CI, providing input on issues & PRs, working on docs, etc), but I'm not an expert in security by any means, so things like approving PRs which affect core functionality should fall to someone more knowledgeable in that area.

**Comment by juanifioren** [comment]
Hello there, so nice to hear there's people interested on helping here. Who would like to be a contributor? I can give access to merge stuff and we can discuss on what to approve.

I'll be reviewing current PR's and try to merge some of them. So far we can start with:

1. Review test pipeline and current version support for Py/Django.
2. Go through all PR's and diff bugs/features/must have.

**Comment by rh0dium** [comment]
I agree with your priority list.   Looking at this there is some #385 seems like the first good step.

**Comment by rh0dium** [comment]
Feel free to add me as a maintainer.

**Comment by meteozond** [comment]
I would like to help here too

**Comment by rh0dium** [comment]
@juanifioren - Ping!

**Comment by rh0dium** [comment]
Anyone want to fork this and maintain it?

**Comment by pope1ni** [comment]
Hi @juanifioren. How would you feel about handing this project over to the [jazzband](https://jazzband.co/) for future maintenance by the community?

**Comment by rh0dium** [comment]
Bad Link?

**Comment by Thorbenl** [comment]
@juanifioren You can add me too! :) I have a few things that are already in develop that would be nice to get released..

**Comment by juanifioren** [comment]
Latest version `v0.8.0` supporting Django 4 and Python 3.11. Please keep contributing guys.
