### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [juanifioren/django-oidc-provider#401]
Could you please consider to use unittest.mock as a fallback?

https://trello.com/c/S6eADbii/64-remove-python-mock
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by pgajdos** [comment]
See
https://build.opensuse.org/package/show/home:pgajdos:python/python-django-oidc-provider
for details, for example for build with python 3.6 and up.

**Comment by juanifioren** [comment]
@pgajdos Thanks for reporting. Replaced with `unittest.mock` on `develop`.

**Comment by pgajdos** [comment]
Thanks Juan.
