### ISSUE TITLE
Send standard claims in token view

### ISSUE THREAD

**Issue by mastnym** [juanifioren/django-oidc-provider#406]
If sending claims in token view is allowed in settings, there is a piece of code which checks if there are any extra scope claims. If so, it sends these, otherwise it sends standard claims:
[https://github.com/juanifioren/django-oidc-provider/blob/master/oidc_provider/lib/utils/token.py#L57](https://github.com/juanifioren/django-oidc-provider/blob/master/oidc_provider/lib/utils/token.py#L57)

On the other hand, at userinfo endpoint, standard claims are sent automatically and extra claims are added if defined.
IMHO, same scenario should be applied to token endpoint as well. Send standard claims and if there are extra claims defined, send those too.

**Comment by juanifioren** [comment]
Fixed on `develop` branch, thanks for reporting @mastnym
