### ISSUE TITLE
test_idtoken_sign_validation not performing any assert

### ISSUE THREAD

**Issue by rsung** [juanifioren/django-oidc-provider#41]
while investigating an issue with public key and signing, I noticed that test_idtoken_sign_validation is always passing because it's not doing an assert.

**Comment by rsung** [comment]
just read through JWS().verify_compact() method and understand why there was no test.  If signature is bad, an exception would be thrown.  It's good enough for me.

**Comment by juanifioren** [comment]
As you said @rsung, that's why.
