### ISSUE TITLE
When client calls oauth2 /authorize endpoint, django login is always presented

### ISSUE THREAD

**Issue by fritzfs** [juanifioren/django-oidc-provider#420]
When client calls oauth2 /authorize endpoint, django login is always presented even if I am logged in another tab. Do I need to pass some special argument on this endpoint to use existing django session if it exists? Thanks! 
PS, I am not using prompt=login in query param.

**Comment by mkalioby** [comment]
I don't get your point, Django sessions in general lives between different tabs as the cookies are sent to domain.

**Comment by fritzfs** [comment]
Sorry, my mistake. I did testing over auth0.com and their "try connection" injects prompt=login so which causes users to log out and force login for each /authorize call.
