### ISSUE TITLE
Authorization redirect is not AngularJs URI pattern compatible

### ISSUE THREAD

**Issue by rsung** [juanifioren/django-oidc-provider#45]
When redirect uri pattern follows AngularJs URI pattern the redirect breaks.  For example, our client's callback URI looks something like https://www.somewebsite.com/#auth.  

It appears that the following line:
query_fragment = parse_qs(uri.fragment)
in authorize.py is dropping "auth" in fragment.

Result is redirect to https://www.somewebsite.com/#token_type...

**Comment by rsung** [comment]
I think following fix would work but waiting from conformation from the client.

query_fragment = parse_qs(uri.fragment,keep_blank_values=True)
 
 https://www.somewebsite.com/#auth=&token_type=bearer&...

**Comment by juanifioren** [comment]
Ok @rsung. Waiting to see how we can solve this. Don't doubt sending a pull request.

**Comment by rsung** [comment]
@juanifioren 

the client is requesting the following format.


https://www.somewebsite.com/#auth?token_type=bearer&

is that breaking standard?

**Comment by juanifioren** [comment]
@rsung for what I understand, yes!

`?` char should not be there.
For example, this is a valid implicit flow redirection:
```
HTTP/1.1 302 Found
  Location: https://client.example.org/cb#
    access_token=SlAV32hkKG
    &token_type=bearer
    &id_token=eyJ0 ... NiJ9.eyJ1c ... I6IjIifX0.DeWt4Qu ... ZXso
    &expires_in=3600
    &state=af0ifjsldkj
```

**Comment by rsung** [comment]
@juanifioren Apparently this is a common problem with AngularJs and oidc.  There are several workaround and we decided to take one of those instead of making any changes to this lib behavior.

**Comment by juanifioren** [comment]
Thanks @rsung for clearing that out.
