### ISSUE TITLE
Only one key supported

### ISSUE THREAD

**Issue by robosung** [juanifioren/django-oidc-provider#46]
We wanted to use multiple keys (per client) and it appears that the library only allows one.

Is there a plan to support multiple keys?

Thanks,
-r

**Comment by juanifioren** [comment]
When you mean "keys per client"... is about **rsa keys** or **client secrets**?

**Comment by juanifioren** [comment]
So @robosung

**Comment by juanifioren** [comment]
Reopen if you want to explain more in details.
