### ISSUE TITLE
Example OIDC provider using Django-allauth

### ISSUE THREAD

**Issue by wayward710** [juanifioren/django-oidc-provider#61]
If it's useful to anyone, I've been working on a project using django-oidc-provider with django-allauth for authentication.  It uses the ExtraScopeClaims class to include information from the social identity providers and the user's group membership in the UserInfo endpoint.  It still needs more testing and documentation, but overall seems to work.  It's up at https://github.com/wayward710/django-oidc-allauth

**Comment by juanifioren** [comment]
Thanks for sharing the project with the community @wayward710. I'll just close the issue (cause is not an issue actually).
Greetings

_-Ignacio_
