### ISSUE TITLE
having hard time installing on windows

### ISSUE THREAD

**Issue by aarsan** [juanifioren/django-oidc-provider#69]
I am trying to install this on Windows 10 and receiving the following error:

    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat). 

Visual C++ 10.0 comes with Visual Studio 10 which is no longer available. Have you run into this? Do you know of a workaround? Thanks!

**Comment by juanifioren** [comment]
Hi @aarsan. Could you please provide more info about this error? When happen this? What you where trying to do?.

_greetings!_

**Comment by aarsan** [comment]
I'm using 64bit Python 3.4.3 and running "pip install django-oidc-provider". It looks like it's going well then fails at the end with the following error:

running build_ext
building 'Crypto.Random.OSRNG.winrandom' extension
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

**Comment by juanifioren** [comment]
Sorry for my acknowledge about Windows. Btw, [did you read this post?](http://stackoverflow.com/questions/27670365/python-pip-install-error-unable-to-find-vcvarsall-bat-tried-all-solutions). It seems to summarize all the anwers about this problem.

**Comment by aarsan** [comment]
Yeah, unfortunately it looks like the pycrypto dependency requires the compiler from a version of Visual Studio which I don't have. Even if I did have it, I was hoping to install this package using a requirements.txt file on multiple machines, which also won't have that compiler. I think the correct solution is to have a Wheel package, which won't require an external compiler. I don't know if that is possible for you to create if the pycrypto dependency does not have one, unfortunately.

**Comment by aarsan** [comment]
Another option is to have your package depend on pycryptodome, which apparently does have a Wheel package, but if most of the people using this are running it on Linux, I don't see why you would do that :)

**Comment by juanifioren** [comment]
I understand, but this package only depends on `pyjwkest`, and this one makes use of `pycrypto`.

**Comment by aarsan** [comment]
That makes it more difficult. I might be out of luck.

**Comment by aarsan** [comment]
Opened an issue with the dependent library:

https://github.com/rohe/pyjwkest/issues/47

**Comment by aarsan** [comment]
in case anyone runs across this, the workaround is to manually install pycrypto first. a wheel package can be found here: http://www.voidspace.org.uk/python/pycrypto-2.6.1/
