### ISSUE TITLE
OIDC_IDTOKEN_SUB_GENERATOR should handle string pointing to function not direct reference to function

### ISSUE THREAD

**Issue by wojtek-fliposports** [juanifioren/django-oidc-provider#70]
__OIDC_IDTOKEN_SUB_GENERATOR__ should handle string pointing to function not direct reference to function.

Currently I'm force to write something like in `settings.py`:
```
from my_app.tools import my_sub_generator
OIDC_IDTOKEN_SUB_GENERATOR = lambda user: my_sub_generator(user)
```

I think better solution is to use:
```
OIDC_IDTOKEN_SUB_GENERATOR = 'my_app.tools.my_sub_generator'
```

**Comment by juanifioren** [comment]
Thanks for reporting this. Added to branch `v0.2.x`. And will be included on version `v0.2.4`.
