### ISSUE TITLE
Skip user consent entirely

### ISSUE THREAD

**Issue by fgaudin** [juanifioren/django-oidc-provider#75]
Hi Juan,

I'm using your app to split a project into multiple smaller projects but we develop all the clients so asking for user consent is irrelevant for us. Would it make sense to add a setting (OIDC_ALWAYS_SKIP_CONSENT?) to completely bypass it?

I can provide a pull request if you're interested.

In the mean time, I'm planning to implement it by adding UserConsent objects on User create and Client create and OIDC_SKIP_CONSENT_EXPIRE = 99999.

**Comment by juanifioren** [comment]
Hi @fgaudin, sorry for the delay.

Thanks for reporting this, is usefull. Added `OIDC_SKIP_CONSENT_ALWAYS`. I'll be bumping a new version soon.

**Comment by fgaudin** [comment]
Awesome! thank you
