### ISSUE TITLE
OpenID Provider Discovery

### ISSUE THREAD

**Issue by cancan101** [juanifioren/django-oidc-provider#8]
Per http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig:
>OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by concatenating the string `/.well-known/openid-configuration` to the Issuer. The syntax and semantics of .well-known are defined in RFC 5785 [RFC5785] and apply to the Issuer value when it contains no path component. openid-configuration MUST point to a JSON document compliant with this specification and MUST be returned using the `application/json` content type.

Currently there is no view for `/.well-known/openid-configuration`.

[pyoidc does support this feature](https://github.com/rohe/pyoidc/search?utf8=%E2%9C%93&q=%22openid-configuration%22) and other libraries expect that as well: [django-oidc-auth](https://github.com/intelie/django-oidc-auth/blob/a3dd1cc3f5371c200e6a29dddc460d2491b402fa/oidc_auth/models.py#L103) and [AWS](http://docs.aws.amazon.com/IAM/latest/UserGuide/identity-providers-oidc-obtain-thumbprint.html).

**Comment by juanifioren** [comment]
Yes @cancan101 ,
We are still working on the core functionality of OIDC (also on OAuth2). Despite that **Discovery** is used by most clients it is optional (like Dynamic Registration). But It SHOULD be implemented in a future.

Thanks for reporting this.

**Comment by juanifioren** [comment]
Added `/.well-known/openid-configuration` endpoint that exposes basic info expected by clients.

3ad316cdca1a2d0989a05e7ce35566fc530706e4
