### ISSUE TITLE
Add support for client JWT token algorithm configuration

### ISSUE THREAD

**Issue by yalis** [juanifioren/django-oidc-provider#86]
Actually the client generate ID Token using RS256 which is the default algorithm according: 

http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

Would be deseable to add support for HS256 and another common algorithms to the client configuration.

**Comment by juanifioren** [comment]
Great idea @yalis !
Would be nice to have that in the admin.

**Comment by juanifioren** [comment]
I create a branch called `feature-jwtalg`. You can select the JWT algorithm from the admin of each Client.

![screenshot from 2016-03-22 16 20 40](https://cloud.githubusercontent.com/assets/5168681/13964849/8a5bfb42-f04a-11e5-9691-0c54a06a50c3.png)

Can you please test it?. I'll be adding test soon.

**Comment by yalis** [comment]
I tested this new feature with the python-social-auth open_id backend and worked great.

Thanks!

**Comment by juanifioren** [comment]
This feature was released on version `v0.3.2`.
