### ISSUE TITLE
`prompt` value is ignored in Authorization endpoint

### ISSUE THREAD

**Issue by wojtek-fliposports** [juanifioren/django-oidc-provider#87]
in section: [3.1.2.3.  Authorization Server Authenticates End-User](http://openid.net/specs/openid-connect-core-1_0.html#Authenticates) we can read:

> The Authorization Server MUST attempt to Authenticate the End-User in the following cases:
> 
> * The End-User is not already Authenticated.
> * The Authentication Request contains the `prompt` parameter with the value `login`. In this case, the Authorization Server MUST reauthenticate the End-User even if the End-User is already authenticated.
> 
> The Authorization Server MUST NOT interact with the End-User in the following case:
> 
> * The Authentication Request contains the `prompt` parameter with the value `none`. In this case, the Authorization Server MUST return an error if an End-User is not already Authenticated or could not be silently Authenticated.
> 

This parameter being ignored.

Maybe something like this patch will help. Only my worries is the last part about log out the user to force login screen. 

```diff
*** django-rest-auth/rest_auth/views.py       2016-03-30 13:24:33.793060288 +0000
--- django-rest-auth/rest_auth/views.py       2016-03-30 13:24:23.457060791 +0000
***************
*** 2,7 ****
--- 2,8 ----

  from Crypto.PublicKey import RSA
  from django.contrib.auth.views import redirect_to_login, logout
+ from django.contrib.auth import logout as auth_logout
  from django.core.urlresolvers import reverse
  from django.http import JsonResponse
  from django.shortcuts import render
***************
*** 60,65 ****
--- 61,67 ----
          self.params.scope = query_dict.get('scope', '').split()
          self.params.state = query_dict.get('state', '')
          self.params.nonce = query_dict.get('nonce', '')
+         self.params.prompt = query_dict.get('prompt', '')

      def validate_params(self):
          try:
***************
*** 85,90 ****
--- 87,98 ----
              raise AuthorizeError(self.params.redirect_uri, 'invalid_request',
                  self.grant_type)

+         if self.is_authentication and self.params.prompt == 'none' and not self.request.user.is_authenticated():
+             raise AuthorizeError(self.params.redirect_uri, 'login_required', self.grant_type)
+
+         if self.is_authentication and self.params.prompt == 'login':
+             auth_logout(self.request)
+
          clean_redirect_uri = urlsplit(self.params.redirect_uri)
          clean_redirect_uri = urlunsplit(clean_redirect_uri._replace(query=''))
          if not (clean_redirect_uri in self.client.redirect_uris):
```

**Comment by wojtek-fliposports** [comment]
@juanifioren Can You discuss with me solution I proposed ?

**Comment by juanifioren** [comment]
Create a new branch for this `feature-prompt`. Check it out. With all the logic for the prompt param.
I'll be working on tests.

**Comment by juanifioren** [comment]
Feature added to branch `v0.3.x`. Thanks for reporting this.
