### ISSUE TITLE
Add support for non-confidential App clients

### ISSUE THREAD

**Issue by WilliamDenniss** [juanifioren/django-oidc-provider#88]
Currently all clients registered by _django-oidc-provider_ require a client secret, however some clients are [not capable](https://tools.ietf.org/html/draft-ietf-oauth-native-apps-01#section-7) of keeping secrets confidential (specifically: downloadable apps).  

If the client has approved the request previously, subsequent requests are auto-approved by _django-oidc-provider_. I recommend not auto-approving requests for non-confidential clients that use URI schemes with no authority (i.e. non-https schemes). This could be achieved by adding an "App" client type with no secret provisioned, so that requests from such clients could be processed differently.

**Comment by WilliamDenniss** [comment]
[This section](https://tools.ietf.org/html/draft-ietf-oauth-native-apps-01#section-5.4) of the Apps draft refers to auto-approval for non-confidential clients.

**Comment by juanifioren** [comment]
Thanks @WilliamDenniss, now if the request comes from a public client the provider won't auto-approve the request. Added to branch `v0.3.x`.
