### ISSUE TITLE
Migrate from Crypto to Cryptodome

### ISSUE THREAD

**Issue by vpmedia** [juanifioren/django-oidc-provider#93]
Hi,
Can you please change the code in the v3 branch importing Crypto to Cryptodome?
I think the Crypto package is no longer maintained (last commit was two years ago).
As reference you can take a look at:
https://github.com/rohe/pyjwkest/commit/d676d16b31119c9da3c8243102d4970b2e3ae177

Best regards!

**Comment by juanifioren** [comment]
Hi @vpmedia sorry for the late reply. `django-oidc-provider` use `pyjwkest==1.0.1` (which is the latest version on PyPi) so still make use Crypto. The solution is that the author of `pyjwkest` release a new version with the Cryptodome lib.

**Comment by juanifioren** [comment]
Related issues:
juanifioren/django-oidc-provider#69
rohe/pyjwkest#47

**Comment by vpmedia** [comment]
Great, thanks for the response!

**Comment by pjsg** [comment]
It is a little unclear which version of django-oidc-provider is really supposed to work. The current version depends on a version of pyjwkest which depends on pycryptodome. Thus all the Crypto references in django-oidc-provider point to pycryptodome. However, this means that you cannot use this version in a python environment that needs the old pycrypto (as pycryptodome is not compatible). 

The current version of pyjwkest uses pycryptodomex instead, which is much more compatible (as it uses a different namespace), but of course means that work is needed in django-oidc-provider to make that work again. 

Which version of django-oidc-provider should I use if I already am using pycrypto (usually forced via other dependencies)?

**Comment by juanifioren** [comment]
@pjsg Hi, you are totally right. My fault since I've never run into this compatibility issue. Uploaded version `v0.4.1` with pyjwkest updated and now using pycryptodomex. So this version will be safe for you.
Greetings!

**Comment by pjsg** [comment]
Thank you.
