### ISSUE TITLE
When I ran the runserver it said that you code needed to be migrated.

### ISSUE THREAD

**Issue by cnobile2012** [juanifioren/django-oidc-provider#96]
It looks like you may have forgotten to commit the last DB migrations to your repo. I get a request when I run the runserver that your code needs migrations. I did makemigrations on your code and it fixed this. When I want to upgrade to a future version, of your code, there will be collisions with migrations, since we both will be making migrations on the same change set.

You may want to check this out and fix it ASAP before too many people run into this issue.

**Comment by juanifioren** [comment]
Hi @cnobile2012.
I can't reproduce this error you describe. What version of `django-oidc-provider` you are using?.
I try running `python manage.py makemigrations oidc_provider` but nothing happens.

**Comment by cnobile2012** [comment]
It looks like it's version 3.3, this is the egg info file
name: django_oidc_provider-0.3.3-py3.4.egg-info

The first time I ran the runserver is when it told me that there were
migrations in your code. I ran `./manage.py makemigrations oidc_provider`
and it made `oidc_provider/migrations/0015_auto_20160608_0030.py` in your
package.

~Carl


On Fri, Jun 10, 2016 at 9:18 AM, Juan Ignacio Fiorentino <
notifications@github.com> wrote:

> Hi @cnobile2012 <https://github.com/cnobile2012>.
> I can't reproduce this error you describe. What version of
> django-oidc-provider you are using?.
> I try running python manage.py makemigrations oidc_provider but nothing
> happens.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/juanifioren/django-oidc-provider/issues/96#issuecomment-225179441>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB4UTWkghxM7Ffa99s_KN5ShMlITZSfxks5qKWQdgaJpZM4Iyg6m>
> .
>



-- 
-------------------------------------------------------------------------------
Carl J. Nobile (Software Engineer)
carl.nobile@gmail.com
-------------------------------------------------------------------------------

**Comment by juanifioren** [comment]
Fixed. Migration added. Check out version `v0.3.4`.
Thanks for reporting this @cnobile2012.
