### ISSUE TITLE
Consider support for both pyjwkest and python-jose

### ISSUE THREAD

**Issue by jdunck** [juanifioren/django-oidc-provider#97]
I have a project that already uses python-jose, and I'd like to use django-oidc-provider as well.   It seems a shame to have multiple implementations of JWT running around, so that there are possibly-conflicting transitive dependencies and interoperability concerns.

It's possible to have library users choose their transitive dependency by using extra_requires:
e.g. 
https://github.com/jazzband/django-constance/blob/8f71bca1924df04274475dd013253ebfee633e93/docs/index.rst#installation
https://github.com/jazzband/django-constance/blob/8f71bca1924df04274475dd013253ebfee633e93/setup.py#L54

Would you consider this approach?  I can do a PR if it sounds like a good idea.

**Comment by juanifioren** [comment]
Ok. How are you going to implement this?.

**Comment by jdunck** [comment]
People would need to change their requirements to 'django-oidc-provider[jwkest]' or 'django-oidc-provider[jose]' - we could keep jwkest by default for a backwards-compat version or whatever you want.

Internally, there would be a jwt-compat module, which tries to import jwkest and falls back to jose, and adapts their APIs to an internal -oidc-provider format.  Or, if you don't like the fall-back approach, then there could be a setting to specify which JWT implementation to use.  Which do you prefer?

**Comment by juanifioren** [comment]
Ok. I would like to leave jwkest as the default one. And I think the fall-back approach is OK. What do you think?. We can create a jose module inside lib folder and put all the logic there.

**Comment by juanifioren** [comment]
We can start working this on [feature-jwtdeps](https://github.com/juanifioren/django-oidc-provider/tree/feature-jwtdeps) branch. I'll try to help you.

**Comment by jdunck** [comment]
OK, I've forked to https://github.com/matterport/django-oidc-provider.

I notice pyjwkest==1.1.0 in setup.py, but 1.1.7 is the current latest.  Want >=1.1.0,<1.2.0?

**Comment by juanifioren** [comment]
Ok. No problem.

**Comment by jdunck** [comment]
Hi @juanifioren  - I've been working on this and didn't see a place where you specify the supported algorithms.  Is it just HS256 and RS256?  I figured I should ask rather than guess. :)

**Comment by juanifioren** [comment]
Hi @jdunck, sorry for the late reply. YES! only those algs are supported btm.
Please anything else just ask.

**Comment by jdunck** [comment]
PR up: https://github.com/juanifioren/django-oidc-provider/pull/103

**Comment by jdunck** [comment]
That one was closed, new one #106

**Comment by jdunck** [comment]
PR was merged, closing this related ticket.

**Comment by juanifioren** [comment]
I'll close this. This feature was not merged.
